name: haskell-scheme
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2018 Author name here
license: BSD3
homepage: https://github.com/jmgreen12/haskell-scheme#readme
extra-source-files:
  - README.md
dependencies:
  - parsec
  - base >=4.7 && <5
  - hspec
library:
  source-dirs: src
  ghc-options: -Wall
executables:
  haskell-scheme:
    main: Main.hs
    source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - haskell-scheme
